/*
 * 码云 Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.3.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gitee

type PutFileParam struct {
	// 用户授权码
	AccessToken string `json:"access_token,omitempty"`
	// 文件内容，采用base64编码
	Content string `json:"content,omitempty"`
	// 文件的Blob Sha，可通过[获取仓库具体路径下的内容]API获取
	Sha string `json:"sha,omitempty"`
	// 提交信息
	Message string `json:"message,omitempty"`
	// 分支名称，默认为仓库的默认分支
	Branch string `json:"branch,omitempty"`
	// Committer名字，默认为当前用户名字
	CommitterName string `json:"committer[name],omitempty"`
	// Committer邮箱，默认为当前用户邮箱
	CommitterEmail string `json:"committer[email],omitempty"`
	// Author名字，默认为当前用户名字
	AuthorName string `json:"author[name],omitempty"`
	// Author邮箱，默认为当前用户邮箱
	AuthorEmail string `json:"author[email],omitempty"`
}
